version: "3.6"

services:
  weather-amqp:
    container_name: weather-amqp
    image: rabbitmq:3.7-alpine
    ports:
      - ${RABBITMQ_PORT}:5672
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
    networks:
      - net

  weather-db:
    container_name: weather-db
    image: postgres:11-alpine
    ports:
      - ${TYPEORM_PORT}:5432
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
    - net

  weather-elastic:
    container_name: weather-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - "bootstrap.memory_lock=true"
      - "cluster.name=docker-cluster"
      - "path.repo=/usr/share/elasticsearch/repo"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTIC_PORT}:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esrepo:/usr/share/elasticsearch/repo
    networks:
      - net

#  weather-nginx: # TODO
#    container_name: weather-nginx
#    build:
#      context: ./docker/nginx
#      dockerfile: ./Dockerfile
#    environment:
#      APP_PORT:
#      NGINX_PORT:
#    image: weather-nginx
#    ports:
#      - ${NGINX_PORT}:80
#    networks:
#    - net

  weather-redis:
    container_name: weather-redis
    image: redis:4-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redisdata:/data
    networks:
      - net

  weather-backend:
    container_name: weather-backend
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    image: weather-backend
    ports:
      - ${NGINX_PORT}:3000
    depends_on:
      - weather-amqp
      - weather-db
      - weather-elastic
      - weather-redis
#    links:
#      - weather-amqp
#      - weather-db
#      - weather-elastic
#      - weather-redis
    volumes:
      - ./uploads:/data/uploads
      - ./logs:/data/logs
    networks:
    - net

networks:
  net:
    driver: bridge

volumes:
  esdata:
    driver: local

  esrepo:
    driver: local

  pgdata:
    driver: local

  redisdata:
    driver: local
